config/routes.rb
Rails.application.routes.draw do
  if ENV["AWS_BUCKET"].present?
    mount Shrine.uppy_s3_multipart(:cache) => '/s3/multipart'
  else
    mount Tus::Server => '/uploads'
  end

  constraints(SubdomainConstraint) do
    get "/apply" => "subdomains#apply"
    get "*url"   => "subdomains#chapter"
    get "/"      => "subdomains#chapter"
  end

  constraints(DomainConstraint) do
    get "*url" => "subdomains#canonical"
    get "/"    => "subdomains#canonical"
  end

  get "/blog/contact/" => redirect("/en/contact")
  get "/blog/about/"   => redirect("/en/about_us")
  get "/blog"          => redirect("http://blog.awesomefoundation.org")
  get "/blog/*path"    => redirect { |params, request| "http://blog.awesomefoundation.org/#{Addressable::URI.escape(params[:path])}" }, :format => false
  get "/apply"         => redirect("/en/submissions/new")

  resources :passwords, :controller => 'clearance/passwords', :only => [:new, :create]

  resources :users, :shallow => true do
    resource :password, :controller => 'clearance/passwords', :only => [:create, :edit, :update]
  end

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resource  :session, controller: :sessions, only: [:new, :create, :destroy]

    get "sign_in",  :to => "sessions#new"
    delete "sign_out", :to => "sessions#destroy"

    resources :users, :only => [:index, :update, :edit] do
      resource :admins, :only => [:create, :destroy]
    end

    resources :chapters, :only => [:index, :show, :new, :create, :edit, :update] do
      resources :finalists, :only => [:index]
      resources :projects,  :only => [:index, :show] do
        resource :winner, :only => [:edit]
      end
      resources :moderations, only: [:index]
      resources :users,     :only => [:index]
    end

    resources :invitations, :only => [:new, :create] do
      resources :acceptances, :only => [:new, :create]
    end

    resources :funded_projects, path: "projects", only: [:index, :show]

    resources :projects, except: [:index, :show] do
      member do
        put "hide"
        put "unhide"
      end
      resources :comments
      resource :winner, :only => [:create, :update, :destroy]
      resource :vote, :only => [:create, :destroy]
      resource :moderation, :only => [] do
        put :confirm_spam
        put :confirm_legit
        put :undo
      end
      resource :project_analysis, :only => [] do
        get "show_or_create", :to => "project_analyses#show_or_create"
      end
    end

    resources :moderations, only: [:index]

    resources :submissions, controller: "projects" do
      collection do
        get "success"
      end
    end

    resources :roles, :only => [:destroy] do
      resource :promotions, :only => [:create, :destroy]
    end

    %w(about_us faq start_a_chapter).each do |page|
      get page, :to => 'high_voltage/pages#show', :id => page
    end

    root :to => 'home#index'
  end

  get "/404", :to => "errors#not_found"
  get "/500", :to => "errors#internal_server_error"

  # All other routes are considered 404s. ActionController::RoutingError
  # will catch them, but that fills our logs with noisy exceptions.
  get '*url', :to => 'errors#not_found'
end

app/views/shared/_analytics.html.erb
<% if Rails.env.production? %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-9594800-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<% else %>
<!-- analytics disabled -->
<% end %>

app/views/shared/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/shared/_footer.html.erb
<footer>
  <p>
    <%= link_to t("layouts.application.about_contact"), about_us_path %>
    <%= link_to t("layouts.application.faq"), faq_path %>

    <%= link_to content_tag("i", nil, :class => "icon-twitter", :title => t("word.twitter")), "https://twitter.com/awesomefound", :target => "_blank" %>
    <%= link_to content_tag("i", nil, :class => "icon-facebook", :title => t("word.facebook")), "https://www.facebook.com/awesomefoundation", :target => "_blank" %>

    <% if signed_in? -%>
      <%= link_to t("layouts.application.sign-out"), sign_out_path, :method => :delete %>
    <% else -%>
      <%= link_to t("layouts.application.sign-in"), sign_in_path %>
    <% end -%>
  </p>

  <p>
    <%= link_to "Български", current_params_with_locale("bg") %>
    <%= link_to "English", current_params_with_locale("en") %>
    <%= link_to "Español", current_params_with_locale("es") %>
    <%= link_to "Français", current_params_with_locale("fr") %>
    <%= link_to "ՀԱՅԵՐԵՆ", current_params_with_locale("hy") %>
    <%= link_to "Nederlands", current_params_with_locale("nl") %>
    <%= link_to "Português", current_params_with_locale("pt") %>
    <%= link_to "Русский", current_params_with_locale("ru") %>
  </p>
</footer>

app/views/shared/_javascript.html.erb
<script>
window.awesomeEnvironment = {}
</script>

<%= javascript_include_tag "application-js" %>

<%= render 'shared/analytics' %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/shared/_lightbox.html.erb
<% content_for :javascript do %>
  <% javascript_tag do %>
    $(document).ready(function() {
      $('.gallery').each(function() {
        $(this).magnificPopup({
          delegate: 'a',
          type: 'image',
          gallery: {
            enabled: true
          },
          image: {
            titleSrc: 'title'
          }
        });
      });
    });
  <% end %>
<% end %>

app/views/shared/_navigation.html.erb
<header class="main" id="header">
  <nav>
    <%= link_to root_path, class: :logo do %>
      <%= image_tag("logo.png", class: "fast-forward", alt: "") %>
      <h1><%= t "layouts.application.main-header" %></h1>
    <% end -%>
    <button class="hamburger" data-controller="hamburger" data-action="click->hamburger#toggle"></button>
    <ol class="flexbox horizontal">
      <li><%= link_to t("layouts.application.home"), root_path, class: :home %></li>
      <li><%= link_to t("layouts.application.about_us"), about_us_path, class: :about_us %></li>
      <li><%= link_to t("layouts.application.chapters"), chapters_path, class: :chapters, data: { controller: "menu-toggle", menu_toggle_target_value: ".chapter-menu", action: "click->menu-toggle#toggle" } %></li>
      <li><%= link_to t("layouts.application.projects"), funded_projects_path, class: :funded_projects %></li>
      <% if signed_in? %>
        <li><%= link_to t("layouts.application.dashboard"), submissions_path, { class: :dashboard } %></li>
      <% end %>
      <li><%= link_to t("layouts.application.apply"), new_submission_path, { class: :apply } %></li>
    </ol>
  </nav>
</header>

<section class="chapter-menu flexbox vertical center">
  <div class="inner-wrapper">
    <h1><%= t("layouts.application.chapter_header") %></h1>
    <section class="chapters in-menu flexbox horizontal wrap">
      <% Chapter.active.visitable.sort_by(&CountrySortCriteria.new(COUNTRY_PRIORITY)).each do |chapter| %>
        <% if display_country?(chapter.country) %>
          <% unless @first_country %>
              </div>
            </article>
          <% end %>
          <article class="country">
            <h3><%= chapter.country %></h3>
            <div class="flexbox horizontal wrap">
        <% end %>
        <p><%= link_to chapter.display_name, chapter %></p>
      <% end %>
      </div>
      </article>
    </section>
  </div>
</section>

app/views/shared/_rssfeed.html.erb
<%= javascript_tag do %>
  jQuery(function($) {
    $("#rss-feeds").rss("<%= rss_feed_url %>",
    {
      ssl: true,
      limit: 6,
      layoutTemplate: '<ol class="feed">{entries}</ol>',
      entryTemplate: '<li class="post"><a href="{url}"><span class="post-date">{formatted_date}</span>{title}</a></li>',
      tokens: {
        formatted_date: function(entry, tokens) {
          date = (new Date(tokens.date)) || Date.now();
          return date.toString('yyyy-MM-dd');
        }
      }
    }
    )
  })
<% end -%>

app/views/shared/_sidebar.html.erb
<button class="hamburger" data-controller="hamburger" data-action="click->hamburger#toggle"></button>

<div class="user-profile-image">
  <%= image_tag(current_user.gravatar_url) %>
</div>

<h2><%= current_user.first_name %> <%= current_user.last_name %></h2>

<ol>
  <li>
    <%= link_to "http://wiki.awesomestudies.org", :target => "_blank" do %>
      <%= t(".trustee-resources") %> <i class="icon-external-link"></i>
    <% end %>
  </li>

  <li><%= link_to t(".edit-profile"), edit_user_path(current_user) %></li>
  <% if current_user.can_invite? %>
    <li><%= link_to t(".invite-trustee"), new_invitation_path %></li>
  <% end %>

  <% if chapter.present? %>
  <li class="section-title">
    <h3><%= chapter.display_name %></h3>
  </li>
  <li><%= link_to t(".projects"), chapter_projects_path(chapter) %></li>
  <% unless chapter.any_chapter? %>
    <li><%= link_to t(".finalists"), chapter_finalists_path(chapter) %></li>
    <li><%= link_to t(".members"), chapter_users_path(chapter) %></li>
  <% end %>
  <% if current_user.can_manage_chapter?(chapter) %>
    <li><%= link_to t(".edit-chapter-profile"), edit_chapter_path(chapter) %></li>
  <% end %>
  <% if current_user.can_moderate_for?(chapter) %>
    <li><%= link_to t(".project-moderation"), chapter_moderations_path(chapter, filter: :all) %></li>
  <% end %>
  <% end %>

  <% if current_user.admin? || current_user.can_create_chapters? %>
    <li class="section-title">
      <h3><%= t(".admin") %></h3>
    </li>

    <% if current_user.can_create_chapters? %>
      <li><%= link_to t(".create-chapter"), new_chapter_path %></li>
    <% end %>

    <% if current_user.admin? %>
      <li><%= link_to t(".view-all-users"), users_path %></li>
      <li><%= link_to t(".project-moderation"), moderations_path %></li>
    <% end %>
  <% end %>
</ol>