config/routes.rb
Rails.application.routes.draw do
  if ENV["AWS_BUCKET"].present?
    mount Shrine.uppy_s3_multipart(:cache) => '/s3/multipart'
  else
    mount Tus::Server => '/uploads'
  end

  constraints(SubdomainConstraint) do
    get "/apply" => "subdomains#apply"
    get "*url"   => "subdomains#chapter"
    get "/"      => "subdomains#chapter"
  end

  constraints(DomainConstraint) do
    get "*url" => "subdomains#canonical"
    get "/"    => "subdomains#canonical"
  end

  get "/blog/contact/" => redirect("/en/contact")
  get "/blog/about/"   => redirect("/en/about_us")
  get "/blog"          => redirect("http://blog.awesomefoundation.org")
  get "/blog/*path"    => redirect { |params, request| "http://blog.awesomefoundation.org/#{Addressable::URI.escape(params[:path])}" }, :format => false
  get "/apply"         => redirect("/en/submissions/new")

  resources :passwords, :controller => 'clearance/passwords', :only => [:new, :create]

  resources :users, :shallow => true do
    resource :password, :controller => 'clearance/passwords', :only => [:create, :edit, :update]
  end

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resource  :session, controller: :sessions, only: [:new, :create, :destroy]

    get "sign_in",  :to => "sessions#new"
    delete "sign_out", :to => "sessions#destroy"

    resources :users, :only => [:index, :update, :edit] do
      resource :admins, :only => [:create, :destroy]
    end

    resources :chapters, :only => [:index, :show, :new, :create, :edit, :update] do
      resources :finalists, :only => [:index]
      resources :projects,  :only => [:index, :show] do
        resource :winner, :only => [:edit]
      end
      resources :moderations, only: [:index]
      resources :users,     :only => [:index]
    end

    resources :invitations, :only => [:new, :create] do
      resources :acceptances, :only => [:new, :create]
    end

    resources :funded_projects, path: "projects", only: [:index, :show]

    resources :projects, except: [:index, :show] do
      member do
        put "hide"
        put "unhide"
      end
      resources :comments
      resource :winner, :only => [:create, :update, :destroy]
      resource :vote, :only => [:create, :destroy]
      resource :moderation, :only => [] do
        put :confirm_spam
        put :confirm_legit
        put :undo
      end
      resource :project_analysis, :only => [] do
        get "show_or_create", :to => "project_analyses#show_or_create"
      end
    end

    resources :moderations, only: [:index]

    resources :submissions, controller: "projects" do
      collection do
        get "success"
      end
    end

    resources :roles, :only => [:destroy] do
      resource :promotions, :only => [:create, :destroy]
    end

    %w(about_us faq start_a_chapter).each do |page|
      get page, :to => 'high_voltage/pages#show', :id => page
    end

    root :to => 'home#index'
  end

  get "/404", :to => "errors#not_found"
  get "/500", :to => "errors#internal_server_error"

  # All other routes are considered 404s. ActionController::RoutingError
  # will catch them, but that fills our logs with noisy exceptions.
  get '*url', :to => 'errors#not_found'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @chapters = Chapter.active.visitable.for_display
    @projects = Project.recent_winners.preload(:primary_photo, :chapter).limit(15)
  end
end

app/views/home/index.html.erb
<% content_for :head do %>
  <%= auto_discovery_link_tag(:atom, funded_projects_url(format: 'xml')) %>
<% end %>

<section class="awesome-wrapper">
  <section class="awesome-projects">
  <% @projects[0..5].each do |project| %>
    <article class="project project-<%= project.id %>">
      <%= link_to project, :class => "image-wrapper" do %>
        <div class="project-name">
          <h2><%= project.title %></h2>
          <p><%= t ".by", :name => project.name %></p>
        </div>
        <div class="funding-chapter">
          <h3><%= image_tag("location_pin_small.png") %> <%= project.chapter.display_name %></h3>
        </div>
        <%= image_tag(project.primary_image.url(:index)) %>
      <% end %>
    </article>
  <% end %>

  <section class="tagline">
    <div class="inner-wrapping">
      <div class="wrapper-2">
        <div class="message">
          <h1><%= t ".title" %></h1>
        </div>
      </div>
    </div>
  </section>

  <% (@projects[6..11] || []).each do |project| %>
    <article class="project project-<%= project.id %>">
      <%= link_to project, :class => "image-wrapper" do %>
        <div class="project-name">
          <h2><%= project.title %></h2>
          <p><%= t ".by", :name => project.name %></p>
        </div>
        <div class="funding-chapter">
          <h3><%= image_tag("location_pin_small.png") %> <%= project.chapter.display_name %></h3>
        </div>
        <%= image_tag(project.primary_image.url(:index)) %>
      <% end %>
    </article>
  <% end %>
  </section>
</section>

<div class="flexbox vertical center">
  <section class="what-how">
    <hgroup>
      <h2><%= t(".funding-html", :amount => funding_amount_for(Project.winner_count)) %> <span class="divider"></span> <%= t(".winner-count-html", :amount => Project.winner_count) %></h2>
    </hgroup>
    <div class="need-funding flexbox horizontal wrap justify-space-around">
      <div class="description">
        <h3><%= t ".what.header" %></h3>
        <p><%= t ".what.body-html" %></p>
      </div>
      <div class="info-graphic">
        <div class="graphic flexbox vertical center">
          <%= image_tag("info_graphic.png") %>
        </div>
      </div>
    </div>
  </section>

  <section class="call-to-action flexbox vertical stretch">
    <div class="button-wrapper">
      <%= link_to t(".call-to-action"), new_submission_path %>
    </div>
  </section>

  <section class ="who-where">
    <hgroup>
      <h2><%= t(".chapter-count-html", :count => Chapter.active.visitable.count) %> <span class="divider"></span> <%= t(".country-count-html", :count => Chapter.active.visitable.country_count) %></h2>
    </hgroup>

    <div class="about-preview flexbox horizontal wrap justify-space-around">
      <div class="mini-map">
        <%= image_tag("mini_map.png") %>
      </div>
      <div class="intro">
        <h3><%= t ".who.header" %></h3>
        <p><%= t ".who.body" %></p>
      </div>
    </div>
  </section>

  <section class="awesome-chapters">
    <% @chapters.each do |chapter| %>
        <%= link_to chapter, :class => "image-wrapper" do %>
          <%= chapter.display_name %>
        <% end %>
    <% end %>
  </section>
</div>