config/routes.rb
Rails.application.routes.draw do
  if ENV["AWS_BUCKET"].present?
    mount Shrine.uppy_s3_multipart(:cache) => '/s3/multipart'
  else
    mount Tus::Server => '/uploads'
  end

  constraints(SubdomainConstraint) do
    get "/apply" => "subdomains#apply"
    get "*url"   => "subdomains#chapter"
    get "/"      => "subdomains#chapter"
  end

  constraints(DomainConstraint) do
    get "*url" => "subdomains#canonical"
    get "/"    => "subdomains#canonical"
  end

  get "/blog/contact/" => redirect("/en/contact")
  get "/blog/about/"   => redirect("/en/about_us")
  get "/blog"          => redirect("http://blog.awesomefoundation.org")
  get "/blog/*path"    => redirect { |params, request| "http://blog.awesomefoundation.org/#{Addressable::URI.escape(params[:path])}" }, :format => false
  get "/apply"         => redirect("/en/submissions/new")

  resources :passwords, :controller => 'clearance/passwords', :only => [:new, :create]

  resources :users, :shallow => true do
    resource :password, :controller => 'clearance/passwords', :only => [:create, :edit, :update]
  end

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resource  :session, controller: :sessions, only: [:new, :create, :destroy]

    get "sign_in",  :to => "sessions#new"
    delete "sign_out", :to => "sessions#destroy"

    resources :users, :only => [:index, :update, :edit] do
      resource :admins, :only => [:create, :destroy]
    end

    resources :chapters, :only => [:index, :show, :new, :create, :edit, :update] do
      resources :finalists, :only => [:index]
      resources :projects,  :only => [:index, :show] do
        resource :winner, :only => [:edit]
      end
      resources :moderations, only: [:index]
      resources :users,     :only => [:index]
    end

    resources :invitations, :only => [:new, :create] do
      resources :acceptances, :only => [:new, :create]
    end

    resources :funded_projects, path: "projects", only: [:index, :show]

    resources :projects, except: [:index, :show] do
      member do
        put "hide"
        put "unhide"
      end
      resources :comments
      resource :winner, :only => [:create, :update, :destroy]
      resource :vote, :only => [:create, :destroy]
      resource :moderation, :only => [] do
        put :confirm_spam
        put :confirm_legit
        put :undo
      end
      resource :project_analysis, :only => [] do
        get "show_or_create", :to => "project_analyses#show_or_create"
      end
    end

    resources :moderations, only: [:index]

    resources :submissions, controller: "projects" do
      collection do
        get "success"
      end
    end

    resources :roles, :only => [:destroy] do
      resource :promotions, :only => [:create, :destroy]
    end

    %w(about_us faq start_a_chapter).each do |page|
      get page, :to => 'high_voltage/pages#show', :id => page
    end

    root :to => 'home#index'
  end

  get "/404", :to => "errors#not_found"
  get "/500", :to => "errors#internal_server_error"

  # All other routes are considered 404s. ActionController::RoutingError
  # will catch them, but that fills our logs with noisy exceptions.
  get '*url', :to => 'errors#not_found'
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:new, :create, :success], if: :embed?

  before_action :require_login, except: [:new, :create, :success]
  before_action :verify_user_can_edit, :only => [:destroy]
  before_action :redirect_to_chapter_or_sign_in, :only => [:index], :if => :chapter_missing?
  before_action :find_chapter

  around_action :set_time_zone, :only => [:index, :show]

  include ApplicationHelper

  def index
    @start_date, @end_date = extract_timeframe
    @short_listed = params[:short_list]

    project_filter = ProjectFilter.new(@chapter.projects).during(@start_date, @end_date)

    # Only display projects that do not require human review
    project_filter.not_pending_moderation

    if params[:short_list]
      project_filter.shortlisted_by(current_user)
    end

    if params[:funded]
      project_filter.funded
    end

    # Signal Score filtering — only applied when explicitly requested via score_min param
    @signal_score_min = params.key?(:score_min) ? params[:score_min].to_f : 0
    @sort_mode = params[:sort] if %w[score_desc score_asc earliest latest random].include?(params[:sort])

    if @signal_score_min > 0
      project_filter.signal_score_above(@signal_score_min)
    end

    case @sort_mode
    when "score_desc"
      project_filter.sort_by_signal_score(:desc)
    when "score_asc"
      project_filter.sort_by_signal_score(:asc)
    when "earliest"
      project_filter.sort_by_date(:asc)
    when "latest"
      project_filter.sort_by_date(:desc)
    when "random"
      project_filter.sort_by_random
    # else: default sort (created_at DESC) applied by ProjectFilter#initialize
    end

    @q = params[:q].to_s.strip

    unless @q.blank?
      project_filter.search(@q)
    end

    # Count projects under moderation for the notification box
    @moderation_count = @chapter.projects_pending_moderation.count

    respond_to do |format|
      format.html do
        @projects = project_filter.page(params[:page]).result.includes(:users, :photos, :real_photos)
        @comments = Comment.where(project_id: @projects.collect(&:id)).includes(:user, :project).viewable_by(user: current_user, chapter: @chapter).by_date

        current_user.mark_last_viewed_chapter(params[:chapter_id])
      end

      format.csv do
        if export_all?
          @projects = Project.during_timeframe(@start_date, @end_date)
        else
          @projects = project_filter.result
        end

        headers["Content-Disposition"] = "attachment; filename=#{@chapter.slug}_export.csv"
        render body: Project.csv_export(@projects), content_type: 'text/csv'
      end
    end
  end

  def new
    render_404 and return if embed? && !@chapter

    @project = Project.new(chapter: @chapter)
  end

  def create
    @project = Project.new(create_project_params)
    @project.set_request_metadata(server_metadata, params[:client_metadata])

    if SpamChecker::Project.new(@project).spam?
      flash[:notice] = t("flash.applications.error")
      render :new
    elsif @project.save
      # Send the application confirmation email
      ProjectMailerJob.perform_async(@project.id)

      redirect_to success_submissions_path({ chapter: @project.chapter, mode: params[:mode] }.reject { |_, v| v.blank? })
    else
      flash.now[:notice] = t("flash.applications.error")
      render :new
    end
  end

  def success
    if params[:chapter]
      @chapter = Chapter.find(params[:chapter].downcase) rescue nil
      @twitter_account = @chapter.twitter_account
    end

    @share_url = root_url
  end

  def show
    @project = Project.find(params[:id])

    @display_project_even_if_hidden = true
    @initial_comments = @project.comments.includes(:user).viewable_by(user: current_user, chapter: @chapter).by_date
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(update_project_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def hide
    @project = Project.find(params[:id])
    @display_project_even_if_hidden = (params[:context] == "show")

    if params[:hidden_reason].present?
      @project.hide!(params[:hidden_reason], current_user)
    else
      @error_message = t("flash.projects.hide-reason-required")
    end

    respond_to do |format|
      format.turbo_stream do
        render "hide", locals: { project: @project }
      end

      format.html do
        flash[:notice] = @error_message

        return_to = params[:return_to] ? URI(params[:return_to]) : URI(chapter_projects_path(@project.chapter))
        return_to.fragment = "project#{@project.id}"

        redirect_to return_to.to_s
      end
    end
  end

  def unhide
    @project = Project.find(params[:id])
    @project.unhide!

    redirect_to chapter_project_path(@project.chapter, @project)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to submissions_path
  end

  private

  def embed?
    params[:mode] == "embed"
  end

  def project_params
    [ :name, :title, :url, :email, :phone, :about_me, :about_project, :chapter_id, :extra_question_1, :extra_question_2, :extra_question_3, :extra_answer_1, :extra_answer_2, :extra_answer_3, :photo_order, :rss_feed_url, :use_for_money, photo_ids_to_delete: [], photos_attributes: [:id, :image, :caption, :sort_order, :_destroy] ]
  end

  def create_project_params
    params.require(:project).permit(project_params)
  end

  def update_project_params
    params.require(:project).permit(project_params + [:funded_on, :funded_description])
  end

  def current_project
    @current_project ||= Project.find(params[:id])
  end
  helper_method :current_project

  def export_all?
    params[:export_all] && current_user.admin?
  end

  def current_chapter_for_user
    @current_chapter_for_user ||= Chapter.current_chapter_for_user(current_user)
  end

  def redirect_to_chapter_or_sign_in
    if current_chapter_for_user
      redirect_to chapter_projects_path(current_chapter_for_user)
    else
      sign_out
      redirect_to sign_in_path, notice: t("flash.permissions.must-have-chapter")
    end
  end

  def verify_user_can_edit
    unless current_user.can_edit_project?(current_project)
      redirect_to chapter_projects_path(current_project.chapter)
    end
  end

  def chapter_missing?
    params[:chapter_id].blank?
  end

  def find_chapter
    if params[:chapter_id]
      @chapter = Chapter.find(params[:chapter_id])
    elsif params[:chapter]
      @chapter = Chapter.friendly.find(params[:chapter].downcase, allow_nil: !embed?)
    end
  end

  def set_time_zone(&block)
    if @chapter
      Time.use_zone(@chapter.time_zone, &block)
    else
      yield
    end
  end

  def server_metadata
    {
      ip_address: real_ip_for_spam_detection,
      user_agent: request.user_agent,
      referrer: request.referer
    }
  end

  def real_ip_for_spam_detection
    # CloudFront-Viewer-Address is the most accurate (requires CloudFront config)
    # Fall back to X-Forwarded-For parsing, then Rails default
    request.headers['CloudFront-Viewer-Address']&.split(':')&.first&.strip ||
      request.headers['X-Forwarded-For']&.split(',')&.first&.strip ||
      request.remote_ip
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def selectable_chapters_for(user)
    any_chapter = Chapter.where(:name => Chapter::ANY_CHAPTER_NAME).first
    if user.admin?
      [any_chapter] + Chapter.where.not(name: Chapter::ANY_CHAPTER_NAME).order(:name)
    else
      [any_chapter] + user.chapters.order(:name)
    end
  end

  def winnable_chapters_for(project)
    if current_user.admin?
      Chapter.visitable.for_display
    else
      project.in_any_chapter? ? current_user.dean_chapters : Array(project.chapter)
    end
  end

  def voting_chapters
    return @voting_chapters if @voting_chapters

    if current_user
      @voting_chapters = current_user.chapters

      if @voting_chapters.include?(@chapter)
        @voting_chapters = [@chapter]
      end
    else
      @voting_chapters = []
    end

    @voting_chapters
  end

  def show_winner_buttons_for(project, options = {})
    if @chapter.any_chapter?
      winnable_chapters = current_user.dean_chapters
    else
      winnable_chapters = [@chapter]
    end
    winnable_chapters.map do |chapter|
      link = link_to(project_winner_path(project, :chapter_id => chapter.id), :remote => true, :method => (project.winner? ? :delete : :post), :class => "mark-as-winner chapter-#{chapter.id}") do
        "#{options[:link_prefix]} #{I18n.t(".winner", name: chapter.name, scope: "projects.project")}".html_safe
      end
      "#{options[:pre]}#{link}#{options[:post]}"
    end.join("").html_safe
  end

  def display_project_actions?(user, project)
    user.can_mark_winner?(project) || user.can_edit_project?(project)
  end

  def checked_attribute_if(value)
    if value
      'checked="checked"'.html_safe
    else
      ''
    end
  end

  def s3_uploader_available?
    ENV['AWS_BUCKET'].present?
  end

  def comment_visibility_icon(comment)
    tag.i(class: "icon icon-#{comment_visibility_class(comment)} comment__visible-icon", title: comment.viewable_by)
  end

  def comment_visibility_class(comment)
    case comment.viewable_by
    when "myself" then
      "user"
    when "chapter" then
      "group"
    when "anyone" then
      "globe"
    end
  end
end

app/views/projects/_hide_form.html.erb
  <section class="filtering <%= 'show-form' if local_assigns[:expanded] %>" data-controller="revealer" data-revealer-expanded-class-value="show-form">
    <% if project.hidden? %>
      <p>
        <%= t(".hidden-details", username: project.hidden_by_user.name, hidden_at: l(project.hidden_at.to_date), reason: project.hidden_reason) %>
        <% unless @display_project_even_if_hidden %>
          (<%= link_to t(".view-application"), chapter_project_path(project.chapter, project), :class => "title" %>)
        <% end %>
      </p>
      <%# only display the unhide button if we are reviewing the whole project %>
      <% if @display_project_even_if_hidden %>
        <div class="unhiding-form">
          <%= button_to t(".unhide"), unhide_project_path(id: project.id), method: :put, class: "hide-action" %>
          <div class="explanation">
            <%= t(".unhiding-explanation") %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="consider-hiding">
        <%= t(".consider-hiding") %>
        <%= link_to t(".hide"), "#", data: { project_id: project.id, action: "click->revealer#reveal" }, class: "hideFormLink" %>
      </div>

      <% if local_assigns[:error_message] %>
        <div class="error"><%= local_assigns[:error_message] %></div>
      <% end %>
      
      <div class="hiding-form">
        <%= form_tag hide_project_path(project), method: :put, class: "hide-form", data: { turbo: true } do %>
          <%= label_tag nil do %>
            <%= t(".hide-reason") %>
            <%= text_field_tag :hidden_reason, "", class: "reason" %>
          <% end %>
          <%= hidden_field_tag :return_to, request.original_url %>
          <%= hidden_field_tag :context, params[:context] || params[:action] %>
          <%= submit_tag t(".hide"), class: "hide-action" %>
        <% end %>
        <p class="hint">
          <%= t(".hiding-explanation") %>
        </p>
      </div>
    <% end %>
  </section>

app/views/projects/_moderation.html.erb
<%= turbo_frame_tag "moderation_actions_#{project.id}" do %>
  <div class="application__moderation-actions flexbox center">
    <% if project.project_moderation.reviewed? %>
      <div class="application__moderation-status <%= project.project_moderation.confirmed_spam? ? "application__moderation-status--alert" : "application__moderation-status--success" %>">
        <strong>
          <%= project.project_moderation.confirmed_spam? ? t(".spam") : t(".not-spam") %>
        </strong>
        (<%= project.project_moderation.reviewed_by.name %>)

        <%= button_to t(".undo"), undo_project_moderation_path(project), method: :put, class: "application__moderation-button", form_class: "inline-block" %>
      </div>
    <% else %>
      <% if project.project_moderation&.triggered&.any? %>
        <%= tag.i(class: "icon-question-sign application__moderation-signals", title: t(".spam-signals", signals: project.project_moderation.triggered.join(', '))) %>
      <% end %>
      <%= button_to confirm_spam_project_moderation_path(project), method: :put, class: "application__moderation-button spam-action" do %>
        <%= tag.i(class: "icon-remove-sign") %> <%= t(".spam") %>
      <% end %>
      <%= button_to confirm_legit_project_moderation_path(project), method: :put, class: "application__moderation-button legit-action" do %>
        <%= t(".not-spam") %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/projects/_project_details.html.erb
<header data-controller="toggler" data-toggler-spin-value="true">
  <div class="title">
    <%= link_to project.title, chapter_project_path(project.chapter, project), :class => "title" %>

    <% if local_assigns[:moderation].present? && project.project_moderation %>
      <%= render "projects/moderation", project: project %>
    <% else %>
    <div class="actions">
      <% if project.shortlisted_by?(current_user) %>
        <%= link_to I18n.t(".awesome", scope: "projects.project", count: 1), project_vote_path(project), :method => :delete, :remote => true, :class => "short-list", data: { chapter: "" } %>
      <% end %>
      <% voting_chapters.each do |voting_chapter| %>
        <%= link_to I18n.t(".awesome", scope: "projects.project", count: voting_chapters.size, chapter: voting_chapter.slug), project_vote_path(project, chapter_id: voting_chapter.id), :method => :post, :remote => true, :class => "short-list", data: { chapter: voting_chapter.id } %>
      <% end %>

      <% if display_project_actions?(current_user, project) %>
        <%= link_to '<i class="icon-gear"></i>'.html_safe, "#", class: "project-actions-toggle", data: { action: "click->toggler#toggle" } %>
      <% end %>
    </div>
    <% end %>

    <div class="public-link">
      <%= link_to funded_project_path(project), target: "blank" do %>
        <%= I18n.t(".view-public-page", scope: "projects.project") %> <i class="icon-ok-sign"></i>
      <% end %>
    </div>
  </div>

  <% signal_score = project.metadata&.dig("signal_score") %>
  <% if signal_score && signal_score["composite_score"] %>
    <%= render "projects/signal_score_badge", signal_score: signal_score, always_show: local_assigns[:full_view] %>
  <% end %>

  <section class="meta-data">
    <%= project.created_at %> (<%= project.chapter.display_name %>)

    <section class="project-actions hidden" data-toggler-target="toggleable">
      <ul class="icons-ul">
        <% if current_user.can_mark_winner?(project) %>
          <li class="non-winner-action">
            <%= link_to edit_chapter_project_winner_path(project.chapter, project, return_to: "#{request.path}#project#{project.id}") do %>
              <i class="icon-li icon-forward"></i>
              <%= t("projects.project.publish-as-winner") %>
            <% end %>
          </li>

          <li class="winner-action">
            <%= link_to edit_chapter_project_winner_path(project.chapter, project, return_to: "#{request.path}#project#{project.id}"), class: "mark-as-winner" do %>
              <i class="icon-li icon-forward"></i> <%= t("projects.project.edit-winner") %>
            <% end %>
          </li>

          <li class="winner-action">
            <%= link_to project_winner_path(project), remote: true, method: :delete, class: "remove-as-winner" do %>
              <i class="icon-li icon-minus"></i>
              <%= t("projects.project.unpublish-as-winner") %>
            <% end %>
          </li>
        <% end %>

        <% if current_user.can_edit_project?(project) %>
          <li>
            <%= link_to edit_project_path(project) do %>
              <i class="icon-li icon-edit"></i> <%= t("projects.project.edit") %>
            <% end %>
          </li>

          <li>
            <%= link_to project_path(project), :method => :delete, :data => { :confirm => I18n.t("projects.project.confirm-delete") }, :class => "text-muted delete-spam" do %>
              <i class="icon-li icon-remove"></i> <%= t("projects.project.delete") %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </section>
  </section>

  <section class="contact">
    <span>
      <%= project.name %>
    </span>

    <span>
      · <%= mail_to project.email %>
    </span>

    <% if project.phone.present? %>
      <span>
        · <%= project.phone %>
      </span>
    <% end %>

    <% if project.url.present? %>
      <span>
        · <%= link_to project.url, project.url, :target => "_blank" %>
      </span>
    <% end %>
  </section>
</header>

<section class="project-proposal-details">
  <div class="project-pitch">
    <% if project.photos.any? %>
      <% if ENV['APPLICATION_IMAGE_PREVIEWS'].present? %>
      <div class="gallery flexbox wrap">
      <% project.photos.each_with_index do |image, index| %>
        <div class="application__image-wrapper">
          <%= link_to(image_path(image.url), rel: "project-#{project.id}-images", class: "lightbox", target: "_blank", title: image.caption) do -%>
            <% if image.image? %>
              <%= image_tag(image.url(:small_square), height: "auto", width: "100%", loading: "lazy") -%>
            <% else %>
              <%= image_tag("document-svgrepo-com.svg", class: "application__image-placeholder") %>
            <% end %>
          <% end %>
        </div>
      <% end %>
      </div>
      <% else %>
      <h3><%= I18n.t(".images", scope: "projects.project") %></h3>
      <p class="gallery">
        <% project.photos.each_with_index do |image, index| %>
          <%= link_to I18n.t(".image", scope: "projects.project", index: index + 1), image_path(image.url), :rel => "project-#{project.id}-images", :class => "lightbox", :target => "blank" %>
        <% end %>
      </p>
    <% end %>
    <% end %>

    <div class="application__body">
    <h3><%= I18n.t(".about-project", scope: "projects.project") %></h3>
    <%= markdown project.about_project, :link_attributes => { :target => "_blank" }, :hard_wrap => true %>
    <h3><%= I18n.t(".use-for-money", scope: "projects.project") %></h3>
    <%= markdown project.use_for_money, :link_attributes => { :target => "_blank" }, :hard_wrap => true %>
    <h3><%= I18n.t(".about-me", scope: "projects.project") %></h3>
    <%= markdown project.about_me, :link_attributes => { :target => "_blank" }, :hard_wrap => true %>

    <% 1.upto(Chapter::EXTRA_QUESTIONS_COUNT) do |num| -%>
      <% if project.extra_question(num).present? %>
        <h3><%= project.extra_question(num) %></h3>
        <%= markdown project.extra_answer(num), :link_attributes => { :target => "_blank" } || "_#{I18n.t '.not-answered', scope: 'projects.project'}_" %>
      <% end %>
    <% end %>
    </div>
  </div>

</section>

  <section class="project__comments">
    <div class="project__comments-inner">
      <%= react_component("CommentList", { projectId: project.id, currentUserId: current_user.id, deleteBasePath: project_comments_path(project), initialComments: @initial_comments, deleteConfirmationText: I18n.t(".confirm-delete-comment", scope: "projects.project"), deleteIconText: I18n.t(".delete-comment", scope: "projects.project"), deletePermission: current_user.can_edit_project?(project) }, { prerender: @initial_comments.present? }) %>

      <div class="comment-form-wrapper" data-controller="revealer">
        <%= link_to I18n.t(".add-comment", scope: "projects.project"), "#", class: "comment-form-expand", data: { action: "click->revealer#reveal" } %>

        <%= simple_form_for [project, Comment.new], method: :post, remote: true, html: { class: "comment-form" } do |f| %>
          <%= f.input :viewable_by, collection: Comment::VIEWABLE_OPTIONS, include_blank: false, wrapper_html: { class: "comment-form__viewable-by" }, label_html: { class: "comment-form__label--inline" } %>
          <%= f.input_field :body, as: :string, class: "comment-form__input--textarea", autocomplete: "off" %>
        <% end %>
      </div>
    </div>
  </section>

app/views/projects/_project_hidden.html.erb
<header>
  <div class="title">
    <%= link_to project.title, chapter_project_path(project.chapter, project), :class => "title" %>
    <% if local_assigns[:moderation].present? && project.project_moderation %>
      <%= render "projects/moderation", project: project %>
    <% end %>
  </div>

  <section class="meta-data">
    <%= project.created_at %> (<%= project.chapter.display_name %>)

    <% if project.winner? %>
      · <%= link_to I18n.t(".view-public-page", scope: "projects.project"), funded_project_path(project), target: "blank" %>
    <% end %>
  </section>

  <section class="contact">
    <span>
      <%= project.name %>
    </span>

    <span>
      · <%= mail_to project.email %>
    </span>

    <% if project.phone.present? %>
      <span>
        · <%= project.phone %>
      </span>
    <% end %>

    <% if project.url.present? %>
      <span>
        · <%= link_to project.url, project.url %>
      </span>
    <% end %>
  </section>
</header>

app/views/projects/public_show.html.erb
<% provide(:page_title, @project.title) %>
<% provide(:meta_description, strip_tags(@project.funded_description.truncate(150))) if @project.funded_description %>
<% provide(:meta_image, image_url(@project.primary_image.url)) if @project.has_images? %>
<% content_for(:extra_body_classes, 'funded_projects-show') %>

<header class="project">
  <% prev_project, next_project = project_winning_siblings(@project) %>
  <% if prev_project || next_project %>
    <div class="prev-next-links">
      <%= link_to t('.prev-project'), prev_project, :class => 'prev-project' if prev_project %>
      <%= link_to t('.next-project'), next_project, :class => 'next-project' if next_project %>
    </div>
  <% end %>
  <% if can_manage_chapter?(@project.chapter) %>
    <%= link_to t(".edit"), edit_project_path(@project), :class => 'edit-project' %>
  <% end %>
  <h1><%= @project.title %></h1>
</header>

<section id="project-gallery" class="flexbox horizontal">
  <% if @project.display_images.count < 5 %>
    <%= render "projects/#{@project.display_images.count}up_gallery", project: @project  %>
  <% else %>
    <%= render "projects/5up_gallery", project: @project %>
  <% end %>
  <% if @project.has_images? %>
    <%= link_to t(".view-photos"), "#", id: "launch-gallery", class: "view-photos" %>
  <% end %>  
</section>

<section class="project-details">
  <section class="meta-data">
    <p><%= t(".byline-html", :chapter_name => link_to(@project.chapter.display_name, chapter_path(@project.chapter)), :submitter_name => @project.name) %></p>
    <div class="addthis_toolbox addthis_default_style ">
      <a class="addthis_button_twitter"></a>
      <a class="addthis_button_facebook"></a>
      <a class="addthis_button_google"></a>
      <a class="addthis_button_email"></a>
      <a class="addthis_button_compact"></a>
      <a class="addthis_counter addthis_bubble_style"></a>
    </div>
    <script type="text/javascript" src="https://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f46fdff2154a73e"></script>
  </section>

  <div class="flexbox horizontal wrap justify-space-between">
    <section class="project-description">
      <% if @project.winner? %>
        <%= markdown @project.funded_description, :link_attributes => { :target => "_blank" }, :hard_wrap => true %>

      <% else %>
        <h2><%= t ".description.header" %></h2>
        <%= markdown @project.about_project %>

        <% if @project.extra_answer_1? %>
          <h2><%= @project.extra_question_1 %></h2>
          <p><%= @project.extra_answer_1 %></p>
        <% end %>

        <% if @project.extra_answer_2? %>
          <h2><%= @project.extra_question_2 %></h2>
          <p><%= @project.extra_answer_2 %></p>
        <% end %>

        <% if @project.extra_answer_3? %>
          <h2><%= @project.extra_question_3 %></h2>
          <p><%= @project.extra_answer_3 %></p>
        <% end %>
      <% end %>
    </section>

    <section class="project-side-bar flexbox vertical flex-1">
      <article class="project-state">
        <% if @project.winner? %>
          <div class="state funded">
            <p><%= t(".funder-html", :name => @project.chapter.name) %> <span class="funded-on">(<%= l @project.funded_on, :format => :funding %>)</span></p>
          </div>
        <% else %>
          <div class="state applied">
            <p><%= t(".submitted-to-html", :name => @project.chapter.name) %></p>
          </div>
        <% end %>
      </article>

      <% if @project.url? %>
        <article class="project-site-link">
          <%= link_to @project.url do %>
            Visit this project's web site
            <span>→</span>
          <% end %>
        </article>
      <% end %>

      <% if @project.rss_feed_url? %>
        <article class="project-rss">
          <h2><%= t ".feed-title" %></h2>
          <section class="rss" id="rss-feeds"></section>
        </article>
        <% content_for :javascript do -%>
          <%= render 'shared/rssfeed', rss_feed_url: @project.rss_feed_url %>
        <% end -%>
      <% end %>
    </section>
  </div>
  
</section>

<% if @project.has_images? %>
<% content_for :javascript do -%>
<script>
  lightGallery(document.getElementById('project-gallery'), {selector: '.image', download: false});
</script>
<% end -%>
<% end %>