config/routes.rb
Rails.application.routes.draw do
  if ENV["AWS_BUCKET"].present?
    mount Shrine.uppy_s3_multipart(:cache) => '/s3/multipart'
  else
    mount Tus::Server => '/uploads'
  end

  constraints(SubdomainConstraint) do
    get "/apply" => "subdomains#apply"
    get "*url"   => "subdomains#chapter"
    get "/"      => "subdomains#chapter"
  end

  constraints(DomainConstraint) do
    get "*url" => "subdomains#canonical"
    get "/"    => "subdomains#canonical"
  end

  get "/blog/contact/" => redirect("/en/contact")
  get "/blog/about/"   => redirect("/en/about_us")
  get "/blog"          => redirect("http://blog.awesomefoundation.org")
  get "/blog/*path"    => redirect { |params, request| "http://blog.awesomefoundation.org/#{Addressable::URI.escape(params[:path])}" }, :format => false
  get "/apply"         => redirect("/en/submissions/new")

  resources :passwords, :controller => 'clearance/passwords', :only => [:new, :create]

  resources :users, :shallow => true do
    resource :password, :controller => 'clearance/passwords', :only => [:create, :edit, :update]
  end

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resource  :session, controller: :sessions, only: [:new, :create, :destroy]

    get "sign_in",  :to => "sessions#new"
    delete "sign_out", :to => "sessions#destroy"

    resources :users, :only => [:index, :update, :edit] do
      resource :admins, :only => [:create, :destroy]
    end

    resources :chapters, :only => [:index, :show, :new, :create, :edit, :update] do
      resources :finalists, :only => [:index]
      resources :projects,  :only => [:index, :show] do
        resource :winner, :only => [:edit]
      end
      resources :moderations, only: [:index]
      resources :users,     :only => [:index]
    end

    resources :invitations, :only => [:new, :create] do
      resources :acceptances, :only => [:new, :create]
    end

    resources :funded_projects, path: "projects", only: [:index, :show]

    resources :projects, except: [:index, :show] do
      member do
        put "hide"
        put "unhide"
      end
      resources :comments
      resource :winner, :only => [:create, :update, :destroy]
      resource :vote, :only => [:create, :destroy]
      resource :moderation, :only => [] do
        put :confirm_spam
        put :confirm_legit
        put :undo
      end
      resource :project_analysis, :only => [] do
        get "show_or_create", :to => "project_analyses#show_or_create"
      end
    end

    resources :moderations, only: [:index]

    resources :submissions, controller: "projects" do
      collection do
        get "success"
      end
    end

    resources :roles, :only => [:destroy] do
      resource :promotions, :only => [:create, :destroy]
    end

    %w(about_us faq start_a_chapter).each do |page|
      get page, :to => 'high_voltage/pages#show', :id => page
    end

    root :to => 'home#index'
  end

  get "/404", :to => "errors#not_found"
  get "/500", :to => "errors#internal_server_error"

  # All other routes are considered 404s. ActionController::RoutingError
  # will catch them, but that fills our logs with noisy exceptions.
  get '*url', :to => 'errors#not_found'
end

app/controllers/finalists_controller.rb
class FinalistsController < ApplicationController
  before_action :must_be_able_to_view_finalists

  around_action :set_time_zone

  include ApplicationHelper

  def index
    @sort = %w(title date).include?(params[:sort]) ? params[:sort] : "votes"

    @start_date, @end_date = extract_timeframe
    @projects = Project.
                  includes(:chapter).
                  with_votes_for_chapter(current_chapter).
                  during_timeframe(@start_date, @end_date).
                  by_vote_count(sort: @sort)

    unless params[:past_trustees].present?
      @projects = @projects.with_votes_by_members_of_chapter(current_chapter)
    end

    unless params[:hidden].present?
      @projects = @projects.where(hidden_at: nil)
    end

    unless params[:funded].present?
      @projects = @projects.where(funded_on: nil)
    end
  end

  private

  def current_chapter
    @chapter ||= Chapter.find_by_id(params[:chapter_id])
  end

  def must_be_able_to_view_finalists
    unless current_user.admin? || current_user.can_view_finalists_for?(current_chapter)
      flash[:notice] = t("flash.permissions.cannot-view-finalists")
      redirect_to submissions_path
    end
  end

  def set_time_zone(&block)
    Time.use_zone(current_chapter.time_zone, &block)
  end
end

app/views/finalists/index.html.erb
<% provide(:page_title, t(".title", name: @chapter.display_name)) %>
<% provide(:meta_viewport, 'width=device-width, initial-scale=1, maximum-scale=1') %>

<section class="admin-panel">
  <%= render 'shared/sidebar', :chapter => @chapter %>
</section>

<section class="applications">
  <h1><%= t ".title", :name => @chapter.display_name %></h1>
  <section class="application-filters flexbox vertical">
    <nav>
      <%= link_to '#', :class => 'chapter-selection' do %>
        <span><%= @chapter.display_name %></span>
        <span class="arrow"></span>
      <% end %>
      <ol class="chapter-selector">
        <% selectable_chapters_for(current_user)[1..-1].each do |chapter| %>
          <li><%= link_to chapter.display_name, chapter_finalists_path(chapter) %></li>
        <% end %>
      </ol>
    </nav>

    <form accept-charset="UTF-8" action="<%= chapter_finalists_path(@chapter) %>" class="simple_form filter" method="get">
      <div class="input string optional date-range">
        <label class="string optional" for="filter_start"><%= t ".start-date" %></label>
        <input class="string optional prefilled" id="filter_start" name="start" size="50" type="text" value="<%= @start_date %>" autocomplete="off">
      </div>

      <div class="input string optional date-range">
        <label class="string optional" for="filter_end"><%= t ".end-date" %></label>
        <input class="string optional prefilled" id="filter_end" name="end" size="50" type="text" value="<%= @end_date %>" autocomplete="off">
      </div>

      <div class="input toggle">
        <%= check_box_tag "past_trustees", nil, params[:past_trustees].present? %>
        <%= label_tag "past_trustees", t(".past-trustees-filter") %>
      </div>

      <div class="input toggle">
        <%= check_box_tag "funded", nil, params[:funded].present? %>
        <%= label_tag "funded", t(".funded-filter") %>
      </div>

      <div class="input toggle">
        <%= check_box_tag "hidden", nil, params[:hidden].present? %>
        <%= label_tag "hidden", t(".hidden-filter") %>
      </div>

      <input name="" type="submit" value="<%= t(".filter-button") %>">
    </form>
  </section>

  <table>
    <tr class="headers">
      <th><%= link_to t(".table.title"), request.params.merge(sort: "title"), class: ("sorted" if @sort == "title") %></th>
      <th><%= link_to t(".table.date"),  request.params.merge(sort: "date"),  class: ("sorted" if @sort == "date") %></th>
      <th><%= link_to t(".table.votes"), request.params.merge(sort: "votes"), class: ("sorted" if @sort == "votes") %></th>
    </tr>
    <% @projects.each do |project| %>
      <tr class="finalist" data-count="<%= project.vote_count %>" data-id="<%= project.id %>">
        <td>
          <%= link_to project.title, chapter_project_path(project.chapter, project) %>
          <%= link_to(raw('<i class="icon-ok-sign winner"></i>'), funded_project_path(project), target: "_blank", title: t("projects.project.winner", name: project.chapter.display_name)) if project.winner? %>
          <% if project.chapter != @chapter %>
            - <em><%= project.chapter.display_name %></em>
          <% end %>
        </td>
        <td><%= project.created_at.strftime("%Y-%m-%d") %></td>
        <td class="vote-count"><%= project.vote_count %></td>
      </tr>
    <% end %>
  </table>
</section>

<% content_for :javascript do %>
  <% javascript_tag do %>
    $(window).load(function(){
      $('#filter_start').datepicker({dateFormat: 'yy-mm-dd', onClose: function(dateText){ $('#filter_start').blur(); $('#filter_end').datepicker('option', 'defaultDate', dateText); $('#filter_end').blur() }});
      $('#filter_end').datepicker({dateFormat: 'yy-mm-dd', onClose: function(){ $('#filter_end').blur() }});
    });
  <% end %>
<% end %>